### ISSUE TITLE
深夜にメモを書いた時 の流れについて

### ISSUE THREAD

**Issue by rakugakijin** [tadashi-aikawa/mobile-first-daily-interface#10]
3/1 にメモを、書いていて、時間が翌日になった時、新しい日(この場合 3/2)のデイリーノートを生成するコマンドが実行されるのか。
偶々 深夜にメモを書いていて、3/1のデイリーノートにも3/2のデイリーノートにもメモが追記されなかった。

**Comment by tadashi-aikawa** [comment]
> 3/1 にメモを、書いていて、時間が翌日になった時、新しい日(この場合 3/2)のデイリーノートを生成するコマンドが実行されるのか。

MDFIの日付が3/1であれば3/2のデイリーノートは生成されません。

【詳細】
https://bsky.app/profile/tadashi-aikawa.bsky.social/post/3kmogiq33v72p
