### ISSUE TITLE
Blueskyで見た時にハッシュタグになっていない

### ISSUE THREAD

**Issue by ginjiro** [tadashi-aikawa/mobile-first-daily-interface#11]
#hogehoge と書いていてBlueskyに投稿しても
Blueskyでハッシュタグとして認識されません

Bluesky側の問題でないのならばハッシュタグに対応してほしいです

**Comment by tadashi-aikawa** [comment]
@ginjiro 
[v1.7.0](https://github.com/tadashi-aikawa/mobile-first-daily-interface/releases/tag/1.7.0) をリリースし、そちらで反映されるようになりました。
