### ISSUE TITLE
コードブロック以外の要素で追記するオプションがほしい

### ISSUE THREAD

**Issue by ginjiro** [tadashi-aikawa/mobile-first-daily-interface#12]
通常このようなMFDIは、
![img|300](https://i.gyazo.com/014bec4ec85eb97ea641ba455047b3ad.jpg)

デイリーノートではこのように表示されるけれど
![img|300](https://i.gyazo.com/2314dcb7d22e070aec1172bd408f8f8f.jpg)

このように表示するオプションがあると便利そう
![img|300](https://i.gyazo.com/bf71b650a40ad2536bd83636f0eff99e.jpg)

MFDI上ではMarkdown記法も反映されますが、デイリーノートではコードブロックとして表示されるのでせっかくのMarkdown記法も無意味になってしまいます。

MFDIから追記された時に日時情報も記録されているので、それを任意のレベルで指定した見出し要素として追記するモードがあれば…

- Markdown記法が無駄にならない
- コアプラグインのアウトラインで順番を入れ替えやすくなる
- ほかのノートから見出しリンクや埋め込み表示できるようになる
- コードブロックじゃない方が流用しやすくなる？

**Comment by tadashi-aikawa** [comment]
@ginjiro 
機能提案ありがとうございます。

今のところ、MFDIはObsidianのノートで見返す行為を目的としていないのですが、見出しであれば、実現はできそうな気がします。

ただ、少し手間はかかりそうなので、他にも同じようなご意見があるかどうかをもう少し観察させてください。

**Comment by tadashi-aikawa** [comment]
@ginjiro 
[v1.10.0](https://github.com/tadashi-aikawa/mobile-first-daily-interface/releases/tag/1.10.0) で対応しました。ご確認ください。
