### ISSUE TITLE
タグに対応してほしい

### ISSUE THREAD

**Issue by villyoshioka** [tadashi-aikawa/mobile-first-daily-interface#13]
MFDIではObsidianと同じようにタグを置こうとするとマークダウンのH1の挙動になってしまいます。
マークダウンで表記しているから仕方がないのかとも思いますが、私のようにタグでメモを管理、分類している身としてはタグが使えるととてもありがたいです。

可能でああればでいいのでご検討いただけますとありがたいです。

**Comment by tadashi-aikawa** [comment]
@villyoshioka 
確認しましたが、タグの表記でH1の挙動にはならないと思います。

![image](https://github.com/tadashi-aikawa/mobile-first-daily-interface/assets/9500018/c9375406-d212-4b52-87ec-b1c047a46b06)

- `# test1` がマークダウンのH1書式 -> H1書式で表示される
- `#test2` がObsidianのタグ書式 -> H1書式で表示されない (期待通り)

**Comment by villyoshioka** [comment]
ご確認ありがとうございます。
こちらの認識不足でした。申し訳ありません。
半角スペースの入らない状態であればH1の挙動にならないことがこちらでも確認できました。

改めて本題のタグ対応ですが、現状では#の後に何か文字を入力してもobsidianのタグとして認識されないようです。

こちら何かまたやり方が悪い等ありますでしょうか？
もしくは対応いただけますと幸いです。

**Comment by tadashi-aikawa** [comment]
@villyoshioka 
> 改めて本題のタグ対応ですが、現状では#の後に何か文字を入力してもobsidianのタグとして認識されないようです。

MFDIの入力内容は、Obsidianのノートではコードブロックとして扱われるため、タグとしては認識されません。これは内部リンク(Internal links)でも同様です。

投稿した内容をコードブロックではなく、平文として入力させたいのであれば以下のIssueに対応する必要があります。そちらをウォッチいただければと思います。

https://github.com/tadashi-aikawa/mobile-first-daily-interface/issues/12

**Comment by tadashi-aikawa** [comment]
@villyoshioka 
v1.10.0で以下のIssueに対応しました。ご確認ください。
https://github.com/tadashi-aikawa/mobile-first-daily-interface/issues/12#issuecomment-2201255995

設定を見出しにすれば、エディタではタグとして認識されることを確認済です。(MFDIで `#` を入力してもタグの候補は表示されませんが...)

**Comment by villyoshioka** [comment]
対応ありがとうございます。
設定を見出しにすれば、エディタではタグとして認識されることをこちらでも確認いたしました。

大規模な仕様変更を伴うもので大変だったかと思いますが対応いただき本当に嬉しいです。

これで自分が使いやすくなるのはもちろんですが、知人にもMFDIを勧めやすくなりました。

これからも応援しております。
