### ISSUE TITLE
インデントしたタスクの表示

### ISSUE THREAD

**Issue by masaki39** [tadashi-aikawa/mobile-first-daily-interface#15]
いつも便利に使わせていただいています。

インデントしたタスクの表示に｢- [ ] ｣ の表記が残ってしまいます。

MDFIからタスクを追加するときには関係ないのですが、後からタスクを分割する時にインデントを使用するので、うまく表示できると嬉しいです。

**Comment by tadashi-aikawa** [comment]
@masaki39 
> インデントしたタスクの表示に｢- [ ] ｣ の表記が残ってしまいます。

こちらの事象について、Sandbox Vaultでの再現手順および結果画像を記載いただけますでしょうか?

※ 事象を把握できていない & 私の方で想像したパターンはすべて問題なく動作したためです

**Comment by tadashi-aikawa** [comment]
インデントしたタスクでも問題なさそうです。(MFDIのタスク表示がインデントに対応していないのは仕様です)
![image](https://github.com/user-attachments/assets/322f669b-e142-41d7-8984-2e515abf6bad)

**Comment by masaki39** [comment]
返信ありがとうございます。
Sandboxで再現しました。

<img width="1440" alt="スクリーンショット 2024-10-14 23 32 27" src="https://github.com/user-attachments/assets/95486b1f-701c-493b-bae5-13f8b8d91143">

手順は
- BRATとMFDIをインストール
- デイリーノートを開いてインデントしたタスクを入力する
のみです。

Obsidianのversionは1.6.7でM1MacBookAir2020を使用しています。

**Comment by tadashi-aikawa** [comment]
@masaki39 
ありがとうございます。インデントにはタブとスペース、どちらを利用されていますでしょうか？

**Comment by masaki39** [comment]
インデントにはタブを使用しています。


2024年10月14日(月) 23:49 Tadashi Aikawa ***@***.***>:

**Comment by tadashi-aikawa** [comment]
@masaki39 
ありがとうございます。インデントをタブにしたら再現しましたので対応します。

**Comment by tadashi-aikawa** [comment]
@masaki39 
v1.11.1で修正しました。ご確認お願いいたします 🙏 
https://github.com/tadashi-aikawa/mobile-first-daily-interface/releases/tag/1.11.1

**Comment by masaki39** [comment]
早急な対応ありがとうございます。
問題なく表示されるようになりました！
