### ISSUE TITLE
ショートカットで投稿

### ISSUE THREAD

**Issue by Foxy-null** [tadashi-aikawa/mobile-first-daily-interface#16]
入力欄で`Ctrl+Enter`などのショートカットを使用して投稿できるようにしていただけたら幸いです。
よろしくお願いいたします。

**Comment by tadashi-aikawa** [comment]
@Foxy-null 
要望ありがとうございます。

以前にこの機能を実装しようとしましたが、簡単にはいかなかったので断念していました。この機会にもう一度チャレンジしてみたいと思います。

**Comment by tadashi-aikawa** [comment]
できましたのでリリースします

※ キーが押されるイベント(KeyDown)だと、Obsidianでキーマップ設定されている場合に検知できない壁がありましたが、キーが引き上げられるイベント(KeyUp)だと拾えそうでした。どちらのイベントでも体験に大きな違いはないと思います..

**Comment by Foxy-null** [comment]
迅速な対応をいただき、ありがとうございました！
