### ISSUE TITLE
リボンメニューの復活またはコマンドパレットから呼び出せるようにしてほしい

### ISSUE THREAD

**Issue by ginjiro** [tadashi-aikawa/mobile-first-daily-interface#8]
v1.3.0からMobile版では左のサイドバーからの使用限定になって呼び出しにくくなった。

左のサイドバーでファイルエクスプローラーやブックマークなどをメインで開いている場合、もどってMFDIを開くまでに数回タップが必要になる。

[![Image from Gyazo](https://i.gyazo.com/cac1837295ce22f0f22c367f77d81208.gif)](https://gyazo.com/cac1837295ce22f0f22c367f77d81208)

今まではリボンメニューがあったのでMobile版のメイン画面から2タップで呼び出せた。
またタブで開いて置いておくこともできた。

現行Versionでもデスクトップ版では右サイドバーに移動できたり、メインウインドウにドラッグして移動して置いておけるが、Mobile版ではそれができない。

要望として、リボンメニューの復活または、コマンドパレットから呼び出せるようにしてほしいです。

**Comment by tadashi-aikawa** [comment]
Issues作成ありがとうございます。検討してみます。

**Comment by tadashi-aikawa** [comment]
@ginjiro 
[v1.4.0](https://github.com/tadashi-aikawa/mobile-first-daily-interface/releases/tag/1.4.0) で対応しました。
