### ISSUE TITLE
obsidian起動時に本プラグインを自動で起動する

### ISSUE THREAD

**Issue by O9PV3** [tadashi-aikawa/mobile-first-daily-interface#9]
obsidianを開いてから、自分の思考やアイデアを記入までの時間を最速にするために、obsidian起動時に必ず本プラグインを起動してノート記入画面が出るようにしてほしいです。

**Comment by tadashi-aikawa** [comment]
Issue作成ありがとうございます :)

オプションで設定追加を検討してみます。

**Comment by tadashi-aikawa** [comment]
@O9PV3 
[v1.5.0](https://github.com/tadashi-aikawa/mobile-first-daily-interface/releases/tag/1.5.0) でリリースしました 🚀
